#!/usr/bin/env python3
"""A campaign session CSV as a tidy table the claim map can read.

    python3 cluster_bringup/campaign/tidy.py <E?_<session>.csv> ...

The harness writes one row per run with the run's parameters encoded in the
arm's name (g32_k5000, t2_cuda_n1000, con_n31000 ...). The claim extractors
select rows by column equality, so this unpacks each arm name into columns and
writes <input>_tidy.csv next to the input:

    session,experiment,arm,family,k,n,rep,wall_s,metric,metric_value

Only valid replicates pass: a warm-up (rep 0) or a rejected run never reaches
a claim. The tidy file is regenerated from the synced raw CSV, committed next
to it, and is what reproduce/claims_campaign_staged.csv points at.

Plain Python 3.6, standard library only.
"""

import csv
import os
import re
import sys

# arm name -> (family, which parameter the number is)
PATTERNS = [
    (re.compile(r"^(cpu|g32|g64|arb)_k(\d+)$"), "k"),
    (re.compile(r"^(t[12]_(?:cpu|cuda|ocl))_n(\d+)$"), "n"),
    (re.compile(r"^(con)_n(\d+)$"), "n"),
    (re.compile(r"^(mpi)_p(\d+)$"), "n"),
    (re.compile(r"^(tree_k(\d+)_g[01])$"), "k_inner"),   # family keeps g0/g1
    (re.compile(r"^((?:gpu|cpu)_(?:uni36|mix_inter|mix_block)|spk_g[01]|spk_id_g[01]"
                r"|g_[a-z0-9_]+|nrn_[a-z_]+|cn_[a-z]+|arbor_gpu"
                r"|ap_[a-z0-9]+|cap_[a-z]+)$"), None),
]


def split_arm(arm):
    for rx, kind in PATTERNS:
        m = rx.match(arm)
        if not m:
            continue
        if kind == "k":
            return m.group(1), m.group(2), ""
        if kind == "n":
            return m.group(1), "", m.group(2)
        if kind == "k_inner":   # tree_k5000_g1 -> family tree_g1, k 5000
            fam = re.sub(r"k\d+_", "", m.group(1))
            return fam, m.group(2), ""
        return m.group(1), "", ""
    return arm, "", ""


def tidy(path):
    with open(path, newline="") as f:
        body = [l for l in f if not l.startswith("#")]
    out = []
    for r in csv.DictReader(body):
        if r.get("status") != "ok" or r.get("rep") in ("0", "", None):
            continue
        fam, k, n = split_arm(r["arm"])
        out.append([r["session"], r["experiment"], r["arm"], fam, k, n,
                    r["rep"], r["wall_s"], r.get("metric", ""), r.get("metric_value", "")])
    dest = path[:-4] + "_tidy.csv"
    with open(dest, "w") as f:
        f.write("# generated by cluster_bringup/campaign/tidy.py from %s -- do not edit\n"
                % os.path.basename(path))
        f.write("session,experiment,arm,family,k,n,rep,wall_s,metric,metric_value\n")
        for row in out:
            f.write(",".join(row) + "\n")
    print("%s: %d valid replicate rows" % (dest, len(out)))
    return dest


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__.strip().split("\n")[2].strip(), file=sys.stderr)
        raise SystemExit(2)
    for p in sys.argv[1:]:
        tidy(p)
